### ISSUE TITLE
Return to WelcomeView from CreateAccountView

### ISSUE THREAD

**Issue by DOOMNOTRON** [hunterthis/IslandStranded#13]
Return back to welcome screen if you accidently select create account view.

**Comment by hunterthis** [comment]
No longer returns to welcome screen, but instead just closes program. Couldn't figure out how to get the console app to shut down, unless installing further packages which I didn't want to add for one function. I'll leave the issue open in case it can get fixed later with a simpler soluation

**Comment by hunterthis** [comment]
actually it functions as intended somewhat so ill close it for now
